# Run the project's test suite
name: Windows tests

on: [pull_request, push]

jobs:
  tests:
    name: Test Python ${{ matrix.python-version }}
    runs-on: windows-latest
    timeout-minutes: 10
    env:
      PYTHON_VERSION: ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.10']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
           auto-update-conda: true
           channels: conda-forge
           python-version: ${{ matrix.python-version }}
           environment-file: requirements/environment.yml
           auto-activate-base: false
      - name: Install Micromamba and setup as executable backend
        shell: bash -l {0}
        run: |
          curl -Ls https://micro.mamba.pm/api/micromamba/win-64/latest | tar -xvj Library/bin/micromamba.exe
          echo "ENV_BACKEND_EXECUTABLE=${{ github.workspace }}\Library\bin\micromamba.exe" >> $GITHUB_ENV
      - name: Install env-manager
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest --cov-report xml --cov=env_manager -vv
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          verbose: true
